// <auto-generated />
using System;
using AntiSpam.Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AntiSpam.Bot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AntiSpam.Bot.Data.Entities.GuildConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AlertChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteMessages")
                        .HasColumnType("boolean");

                    b.Property<bool>("DetectNewUserLinks")
                        .HasColumnType("boolean");

                    b.Property<int>("DetectionWindowSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MinChannelsForSpam")
                        .HasColumnType("integer");

                    b.Property<int>("MuteDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("MuteOnSpam")
                        .HasColumnType("boolean");

                    b.Property<int>("NewUserHoursThreshold")
                        .HasColumnType("integer");

                    b.Property<double>("SimilarityThreshold")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("AntiSpam.Bot.Data.Entities.SpamIncident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AlertChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AlertMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ChannelIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("HandledByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("HandledByUsername")
                        .HasColumnType("text");

                    b.Property<string>("ModeratorNote")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlertMessageId");

                    b.HasIndex("GuildId");

                    b.HasIndex("Status");

                    b.HasIndex("GuildId", "Status");

                    b.ToTable("SpamIncidents");
                });
#pragma warning restore 612, 618
        }
    }
}
