apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  discord-token: {{ .Values.discord.token | quote }}
  discord-owner-id: {{ .Values.discord.ownerId | quote }}
  postgres-password: {{ .Values.postgresql.password | quote }}
  encryption-key: {{ .Values.encryption.key | quote }}
  internal-api-key: {{ .Values.internal.apiKey | quote }}
